spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

net:
  javaguide:
    banking:
      jwtSecret: wskskamokao2ki3j8qjmaknsinsimaoamaok
      jwtExpirationMs: 86400000
    favoriteproducts:
      jwtCookieName: favoriteProducts
